console-error: "&cConsole can't reply to messages!"
no-reply: "&cYou have no one to reply to!"
offline-player: "&cThis player is offline"
unknown-player: "&cNo player found!"
no-message: "&cNo message was entered!"
usage: "&cNo player name was entered. Correct usage: /%s <player-name> <message>"
