name: BetterMsgPlus
version: ${project.version}
main: me.polishkrowa.BetterMsgPlus.MsgPlus
api-version: 1.16

commands:
  tell:
    description: Command to private message players
    aliases: [msg, w]
  reply:
    description: Command to reply to another player's private message(s)
    aliases: [r]
